<a href="https://colab.research.google.com/github/SajidMaqbool/SajidMaqbool/blob/main/F2023065305_Regex_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
# NLP Assignment: Text Preprocessing and Regular Expressions

## Course: Natural Language Processing (CC438)
## Instructor: Mr. Waqar Ashiq
## Topic: Text Preprocessing & Regular Expressions (Regex)

 **Import Libraries**

In [65]:
# Import Required Libraries
import pandas as pd
import re
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download required NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

print("✅ All libraries imported successfully!")
print("✅ NLTK data downloaded successfully!")

✅ All libraries imported successfully!
✅ NLTK data downloaded successfully!

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

**COVID Tweets as Data Set**

In [38]:
# Create COVID-19 Tweets Dataset (12 samples with noise)

data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    'Text': [
        "Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123",
        "WHO reports 50,000 new cases today! @WHO @CDC #Pandemic",
        "Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks",
        "RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789",
        "Covid cases increased by 25% this week #Coronavirus @nytimes",
        "BREAKING: New variant detected in South Africa! #Omicron @WHO",
        "Plz wear mask & maintain social distance 🙏 #StaySafe #COVID",
        "Hospitalizations up by 1000 patients this month!!! @CDCgov",
        "Booster dose available for 18+ from March 1st #BoosterDose",
        "Fake news about COVID cure circulating again!! #StopMisinformation",
        "Total deaths reached 6.5M worldwide 💔 #RIP #COVID19",
        "RT @gov: Lockdown extended until April 15th https://t.co/def456 @official"
    ]
}

df = pd.DataFrame(data)
pd.set_option('display.max_colwidth', None)

print("="*70)
print("📊 ORIGINAL COVID TWEETS DATASET (12 Samples)")
print("="*70)
df

======================================================================
📊 ORIGINAL COVID TWEETS DATASET (12 Samples)
======================================================================

,ID,Text
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov
8,9,Booster dose available for 18+ from March 1st #BoosterDose
9,10,Fake news about COVID cure circulating again!! #StopMisinformation
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official

**Removing URLs**

In [70]:
# Task 1: Remove URLs from tweets

def remove_urls(text):
    """
    Remove URLs from text using regex pattern
    Pattern matches: http://, https://, and www. URLs
    """
    pattern = r'https?://\S+|www\.\S+'
    return re.sub(pattern, '', text)

# Apply the function to create new column
df['No_URLs'] = df['Text'].apply(remove_urls)

print("="*70)
print("📌 AFTER REMOVING URLS")
print("="*70)
print("\n🔹 Before vs After URL Removal:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['Text']}")
    print(f"After:  {row['No_URLs']}")
    print("-"*60)

# Display full dataframe
display(df)

======================================================================
📌 AFTER REMOVING URLS
======================================================================

🔹 Before vs After URL Removal:


ID 1:
Before: Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123
After:  Just tested positive for COVID-19 😢 #COVID19
------------------------------------------------------------

ID 2:
Before: WHO reports 50,000 new cases today! @WHO @CDC #Pandemic
After:  WHO reports 50,000 new cases today! @WHO @CDC #Pandemic
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks
After:  Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks
------------------------------------------------------------

ID 4:
Before: RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789
After:  RT @healthmin: Mask up! Cases rising again in Europe
------------------------------------------------------------

ID 5:
Before: Covid cases increased by 25% this week #Coronavirus @nytimes
After:  Covid cases increased by 25% this week #Coronavirus @nytimes
------------------------------------------------------------

ID 6:
Before: BREAKING: New variant detected in South Africa! #Omicron @WHO
After:  BREAKING: New variant detected in South Africa! #Omicron @WHO
------------------------------------------------------------

ID 7:
Before: Plz wear mask & maintain social distance 🙏 #StaySafe #COVID
After:  Plz wear mask & maintain social distance 🙏 #StaySafe #COVID
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by 1000 patients this month!!! @CDCgov
After:  Hospitalizations up by 1000 patients this month!!! @CDCgov
------------------------------------------------------------

ID 9:
Before: Booster dose available for 18+ from March 1st #BoosterDose
After:  Booster dose available for 18+ from March 1st #BoosterDose
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again!! #StopMisinformation
After:  Fake news about COVID cure circulating again!! #StopMisinformation
------------------------------------------------------------

ID 11:
Before: Total deaths reached 6.5M worldwide 💔 #RIP #COVID19
After:  Total deaths reached 6.5M worldwide 💔 #RIP #COVID19
------------------------------------------------------------

ID 12:
Before: RT @gov: Lockdown extended until April 15th https://t.co/def456 @official
After:  RT @gov: Lockdown extended until April 15th  @official
------------------------------------------------------------

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th

**Removing Mentions**

In [71]:
# Task 2: Remove Mentions (@username)

def remove_mentions(text):
    """
    Remove mentions from text using regex pattern
    Pattern matches: @username (words starting with @)
    """
    pattern = r'@\w+'
    return re.sub(pattern, '', text)

# Apply the function to create new column
df['No_Mentions'] = df['No_URLs'].apply(remove_mentions)

print("="*70)
print("📌 TASK 2: AFTER REMOVING MENTIONS (@username)")
print("="*70)

print("\n🔹 Before vs After Mention Removal:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['No_URLs']}")
    print(f"After:  {row['No_Mentions']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER MENTION REMOVAL")
print("="*70)
display(df)

======================================================================
📌 TASK 2: AFTER REMOVING MENTIONS (@username)
======================================================================

🔹 Before vs After Mention Removal:


ID 1:
Before: Just tested positive for COVID-19 😢 #COVID19
After:  Just tested positive for COVID-19 😢 #COVID19
------------------------------------------------------------

ID 2:
Before: WHO reports 50,000 new cases today! @WHO @CDC #Pandemic
After:  WHO reports 50,000 new cases today!   #Pandemic
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks
After:  Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks
------------------------------------------------------------

ID 4:
Before: RT @healthmin: Mask up! Cases rising again in Europe
After:  RT : Mask up! Cases rising again in Europe
------------------------------------------------------------

ID 5:
Before: Covid cases increased by 25% this week #Coronavirus @nytimes
After:  Covid cases increased by 25% this week #Coronavirus
------------------------------------------------------------

ID 6:
Before: BREAKING: New variant detected in South Africa! #Omicron @WHO
After:  BREAKING: New variant detected in South Africa! #Omicron
------------------------------------------------------------

ID 7:
Before: Plz wear mask & maintain social distance 🙏 #StaySafe #COVID
After:  Plz wear mask & maintain social distance 🙏 #StaySafe #COVID
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by 1000 patients this month!!! @CDCgov
After:  Hospitalizations up by 1000 patients this month!!!
------------------------------------------------------------

ID 9:
Before: Booster dose available for 18+ from March 1st #BoosterDose
After:  Booster dose available for 18+ from March 1st #BoosterDose
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again!! #StopMisinformation
After:  Fake news about COVID cure circulating again!! #StopMisinformation
------------------------------------------------------------

ID 11:
Before: Total deaths reached 6.5M worldwide 💔 #RIP #COVID19
After:  Total deaths reached 6.5M worldwide 💔 #RIP #COVID19
------------------------------------------------------------

ID 12:
Before: RT @gov: Lockdown extended until April 15th  @official
After:  RT : Lockdown extended until April 15th
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER MENTION REMOVAL
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th

**Removing Hashtags**

In [72]:
# Task 3: Extract Hashtags (#topic)

def extract_hashtags(text):
    """
    Extract hashtags from text using regex pattern
    Pattern matches: #word (hashtags)
    Returns the extracted hashtags as a list
    """
    pattern = r'#\w+'
    hashtags = re.findall(pattern, text)
    return hashtags

# Apply the function to create new column
df['Hashtags'] = df['No_Mentions'].apply(extract_hashtags)

# Also remove hashtags from the main text (optional for cleaning)
def remove_hashtags(text):
    """
    Remove hashtags from text
    """
    pattern = r'#\w+'
    return re.sub(pattern, '', text)

df['No_Hashtags'] = df['No_Mentions'].apply(remove_hashtags)

print("="*70)
print("📌 TASK 3: HASHTAG EXTRACTION & REMOVAL")
print("="*70)

print("\n🔹 Before vs After Hashtag Removal:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['No_Mentions']}")
    print(f"After:  {row['No_Hashtags']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER HASHTAG EXTRACTION & REMOVAL")
print("="*70)
display(df)

======================================================================
📌 TASK 3: HASHTAG EXTRACTION & REMOVAL
======================================================================

🔹 Before vs After Hashtag Removal:


ID 1:
Before: Just tested positive for COVID-19 😢 #COVID19
After:  Just tested positive for COVID-19 😢
------------------------------------------------------------

ID 2:
Before: WHO reports 50,000 new cases today!   #Pandemic
After:  WHO reports 50,000 new cases today!
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks
After:  Get vaccinated ASAP!! 💉 Vaccines save lives
------------------------------------------------------------

ID 4:
Before: RT : Mask up! Cases rising again in Europe
After:  RT : Mask up! Cases rising again in Europe
------------------------------------------------------------

ID 5:
Before: Covid cases increased by 25% this week #Coronavirus
After:  Covid cases increased by 25% this week
------------------------------------------------------------

ID 6:
Before: BREAKING: New variant detected in South Africa! #Omicron
After:  BREAKING: New variant detected in South Africa!
------------------------------------------------------------

ID 7:
Before: Plz wear mask & maintain social distance 🙏 #StaySafe #COVID
After:  Plz wear mask & maintain social distance 🙏
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by 1000 patients this month!!!
After:  Hospitalizations up by 1000 patients this month!!!
------------------------------------------------------------

ID 9:
Before: Booster dose available for 18+ from March 1st #BoosterDose
After:  Booster dose available for 18+ from March 1st
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again!! #StopMisinformation
After:  Fake news about COVID cure circulating again!!
------------------------------------------------------------

ID 11:
Before: Total deaths reached 6.5M worldwide 💔 #RIP #COVID19
After:  Total deaths reached 6.5M worldwide 💔
------------------------------------------------------------

ID 12:
Before: RT : Lockdown extended until April 15th
After:  RT : Lockdown extended until April 15th
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER HASHTAG EXTRACTION & REMOVAL
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th

**Remove Numbers**

In [73]:
# Task 4: Remove Numbers

def remove_numbers(text):
    """
    Remove numbers from text using regex pattern
    Pattern matches: digits (0-9)
    """
    pattern = r'\d+'
    return re.sub(pattern, '', text)

# Apply the function to create new column
df['No_Numbers'] = df['No_Hashtags'].apply(remove_numbers)

print("="*70)
print("📌 TASK 4: AFTER REMOVING NUMBERS")
print("="*70)

print("\n🔹 Before vs After Number Removal:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['No_Hashtags']}")
    print(f"After:  {row['No_Numbers']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER NUMBER REMOVAL")
print("="*70)
display(df)

======================================================================
📌 TASK 4: AFTER REMOVING NUMBERS
======================================================================

🔹 Before vs After Number Removal:


ID 1:
Before: Just tested positive for COVID-19 😢
After:  Just tested positive for COVID- 😢
------------------------------------------------------------

ID 2:
Before: WHO reports 50,000 new cases today!
After:  WHO reports , new cases today!
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP!! 💉 Vaccines save lives
After:  Get vaccinated ASAP!! 💉 Vaccines save lives
------------------------------------------------------------

ID 4:
Before: RT : Mask up! Cases rising again in Europe
After:  RT : Mask up! Cases rising again in Europe
------------------------------------------------------------

ID 5:
Before: Covid cases increased by 25% this week
After:  Covid cases increased by % this week
------------------------------------------------------------

ID 6:
Before: BREAKING: New variant detected in South Africa!
After:  BREAKING: New variant detected in South Africa!
------------------------------------------------------------

ID 7:
Before: Plz wear mask & maintain social distance 🙏
After:  Plz wear mask & maintain social distance 🙏
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by 1000 patients this month!!!
After:  Hospitalizations up by  patients this month!!!
------------------------------------------------------------

ID 9:
Before: Booster dose available for 18+ from March 1st
After:  Booster dose available for + from March st
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again!!
After:  Fake news about COVID cure circulating again!!
------------------------------------------------------------

ID 11:
Before: Total deaths reached 6.5M worldwide 💔
After:  Total deaths reached .M worldwide 💔
------------------------------------------------------------

ID 12:
Before: RT : Lockdown extended until April 15th
After:  RT : Lockdown extended until April th
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER NUMBER REMOVAL
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th

**Remoce Special Character**

In [76]:
# Task 5: Remove Punctuation and Special Characters

def remove_punctuation(text):
    """
    Remove punctuation and special characters from text
    Pattern matches: any character that is not a letter or space
    """
    # Keep only letters (a-z, A-Z) and spaces
    pattern = r'[^a-zA-Z\s]'
    return re.sub(pattern, '', text)

# Apply the function to create new column
df['No_Punctuation'] = df['No_Numbers'].apply(remove_punctuation)

print("="*70)
print("📌 TASK 5: AFTER REMOVING PUNCTUATION & SPECIAL CHARACTERS")
print("="*70)

print("\n🔹 Before vs After Punctuation Removal:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['No_Numbers']}")
    print(f"After:  {row['No_Punctuation']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER PUNCTUATION REMOVAL")
print("="*70)
display(df)

======================================================================
📌 TASK 5: AFTER REMOVING PUNCTUATION & SPECIAL CHARACTERS
======================================================================

🔹 Before vs After Punctuation Removal:


ID 1:
Before: Just tested positive for COVID- 😢
After:  Just tested positive for COVID
------------------------------------------------------------

ID 2:
Before: WHO reports , new cases today!
After:  WHO reports  new cases today
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP!! 💉 Vaccines save lives
After:  Get vaccinated ASAP  Vaccines save lives
------------------------------------------------------------

ID 4:
Before: RT : Mask up! Cases rising again in Europe
After:  RT  Mask up Cases rising again in Europe
------------------------------------------------------------

ID 5:
Before: Covid cases increased by % this week
After:  Covid cases increased by  this week
------------------------------------------------------------

ID 6:
Before: BREAKING: New variant detected in South Africa!
After:  BREAKING New variant detected in South Africa
------------------------------------------------------------

ID 7:
Before: Plz wear mask & maintain social distance 🙏
After:  Plz wear mask  maintain social distance
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by  patients this month!!!
After:  Hospitalizations up by  patients this month
------------------------------------------------------------

ID 9:
Before: Booster dose available for + from March st
After:  Booster dose available for  from March st
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again!!
After:  Fake news about COVID cure circulating again
------------------------------------------------------------

ID 11:
Before: Total deaths reached .M worldwide 💔
After:  Total deaths reached M worldwide
------------------------------------------------------------

ID 12:
Before: RT : Lockdown extended until April th
After:  RT  Lockdown extended until April th
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER PUNCTUATION REMOVAL
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers,No_Punctuation
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢,Just tested positive for COVID
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!",WHO reports new cases today
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP Vaccines save lives
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,RT Mask up Cases rising again in Europe
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week,Covid cases increased by this week
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!,BREAKING New variant detected in South Africa
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏,Plz wear mask maintain social distance
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!,Hospitalizations up by patients this month
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st,Booster dose available for from March st
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔,Total deaths reached M worldwide
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th,RT Lockdown extended until April th

**Removing Multiple Sapces and replcaing with single one**

In [77]:
# Task 6: Replace Multiple Spaces with Single Space

def remove_extra_spaces(text):
    """
    Replace multiple spaces with a single space
    Pattern matches: one or more whitespace characters
    """
    pattern = r'\s+'
    return re.sub(pattern, ' ', text).strip()

# Apply the function to create new column
df['Cleaned_Regex'] = df['No_Punctuation'].apply(remove_extra_spaces)

print("="*70)
print("📌 TASK 6: AFTER REPLACING MULTIPLE SPACES")
print("="*70)

print("\n🔹 Before vs After Space Consolidation:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['No_Punctuation']}")
    print(f"After:  {row['Cleaned_Regex']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER ALL REGEX CLEANING STEPS")
print("="*70)
display(df)

======================================================================
📌 TASK 6: AFTER REPLACING MULTIPLE SPACES
======================================================================

🔹 Before vs After Space Consolidation:


ID 1:
Before: Just tested positive for COVID
After:  Just tested positive for COVID
------------------------------------------------------------

ID 2:
Before: WHO reports  new cases today
After:  WHO reports new cases today
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP  Vaccines save lives
After:  Get vaccinated ASAP Vaccines save lives
------------------------------------------------------------

ID 4:
Before: RT  Mask up Cases rising again in Europe
After:  RT Mask up Cases rising again in Europe
------------------------------------------------------------

ID 5:
Before: Covid cases increased by  this week
After:  Covid cases increased by this week
------------------------------------------------------------

ID 6:
Before: BREAKING New variant detected in South Africa
After:  BREAKING New variant detected in South Africa
------------------------------------------------------------

ID 7:
Before: Plz wear mask  maintain social distance
After:  Plz wear mask maintain social distance
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by  patients this month
After:  Hospitalizations up by patients this month
------------------------------------------------------------

ID 9:
Before: Booster dose available for  from March st
After:  Booster dose available for from March st
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again
After:  Fake news about COVID cure circulating again
------------------------------------------------------------

ID 11:
Before: Total deaths reached M worldwide
After:  Total deaths reached M worldwide
------------------------------------------------------------

ID 12:
Before: RT  Lockdown extended until April th
After:  RT Lockdown extended until April th
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER ALL REGEX CLEANING STEPS
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers,No_Punctuation,Cleaned_Regex
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢,Just tested positive for COVID,Just tested positive for COVID
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!",WHO reports new cases today,WHO reports new cases today
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP Vaccines save lives,Get vaccinated ASAP Vaccines save lives
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,RT Mask up Cases rising again in Europe,RT Mask up Cases rising again in Europe
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week,Covid cases increased by this week,Covid cases increased by this week
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!,BREAKING New variant detected in South Africa,BREAKING New variant detected in South Africa
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏,Plz wear mask maintain social distance,Plz wear mask maintain social distance
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!,Hospitalizations up by patients this month,Hospitalizations up by patients this month
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st,Booster dose available for from March st,Booster dose available for from March st
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again,Fake news about COVID cure circulating again
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔,Total deaths reached M worldwide,Total deaths reached M worldwide
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th,RT Lockdown extended until April th,RT Lockdown extended until April th

**Preprocessing**

**Tokenization**

In [79]:
# NLP Preprocessing - Step 1: Tokenization

def tokenize_text(text):
    """
    Split text into individual words (tokens)
    Using NLTK's word_tokenize function
    """
    return word_tokenize(text)

# Apply tokenization to create new column
df['Tokens'] = df['Cleaned_Regex'].apply(tokenize_text)

print("="*70)
print("📌 NLP STEP 1: TOKENIZATION")
print("="*70)

print("\n🔹 Before vs After Tokenization:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['Cleaned_Regex']}")
    print(f"After:  {row['Tokens']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER TOKENIZATION")
print("="*70)
display(df)

======================================================================
📌 NLP STEP 1: TOKENIZATION
======================================================================

🔹 Before vs After Tokenization:


ID 1:
Before: Just tested positive for COVID
After:  ['Just', 'tested', 'positive', 'for', 'COVID']
------------------------------------------------------------

ID 2:
Before: WHO reports new cases today
After:  ['WHO', 'reports', 'new', 'cases', 'today']
------------------------------------------------------------

ID 3:
Before: Get vaccinated ASAP Vaccines save lives
After:  ['Get', 'vaccinated', 'ASAP', 'Vaccines', 'save', 'lives']
------------------------------------------------------------

ID 4:
Before: RT Mask up Cases rising again in Europe
After:  ['RT', 'Mask', 'up', 'Cases', 'rising', 'again', 'in', 'Europe']
------------------------------------------------------------

ID 5:
Before: Covid cases increased by this week
After:  ['Covid', 'cases', 'increased', 'by', 'this', 'week']
------------------------------------------------------------

ID 6:
Before: BREAKING New variant detected in South Africa
After:  ['BREAKING', 'New', 'variant', 'detected', 'in', 'South', 'Africa']
------------------------------------------------------------

ID 7:
Before: Plz wear mask maintain social distance
After:  ['Plz', 'wear', 'mask', 'maintain', 'social', 'distance']
------------------------------------------------------------

ID 8:
Before: Hospitalizations up by patients this month
After:  ['Hospitalizations', 'up', 'by', 'patients', 'this', 'month']
------------------------------------------------------------

ID 9:
Before: Booster dose available for from March st
After:  ['Booster', 'dose', 'available', 'for', 'from', 'March', 'st']
------------------------------------------------------------

ID 10:
Before: Fake news about COVID cure circulating again
After:  ['Fake', 'news', 'about', 'COVID', 'cure', 'circulating', 'again']
------------------------------------------------------------

ID 11:
Before: Total deaths reached M worldwide
After:  ['Total', 'deaths', 'reached', 'M', 'worldwide']
------------------------------------------------------------

ID 12:
Before: RT Lockdown extended until April th
After:  ['RT', 'Lockdown', 'extended', 'until', 'April', 'th']
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER TOKENIZATION
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers,No_Punctuation,Cleaned_Regex,Tokens
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢,Just tested positive for COVID,Just tested positive for COVID,"[Just, tested, positive, for, COVID]"
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!",WHO reports new cases today,WHO reports new cases today,"[WHO, reports, new, cases, today]"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP Vaccines save lives,Get vaccinated ASAP Vaccines save lives,"[Get, vaccinated, ASAP, Vaccines, save, lives]"
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,RT Mask up Cases rising again in Europe,RT Mask up Cases rising again in Europe,"[RT, Mask, up, Cases, rising, again, in, Europe]"
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week,Covid cases increased by this week,Covid cases increased by this week,"[Covid, cases, increased, by, this, week]"
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!,BREAKING New variant detected in South Africa,BREAKING New variant detected in South Africa,"[BREAKING, New, variant, detected, in, South, Africa]"
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏,Plz wear mask maintain social distance,Plz wear mask maintain social distance,"[Plz, wear, mask, maintain, social, distance]"
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!,Hospitalizations up by patients this month,Hospitalizations up by patients this month,"[Hospitalizations, up, by, patients, this, month]"
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st,Booster dose available for from March st,Booster dose available for from March st,"[Booster, dose, available, for, from, March, st]"
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again,Fake news about COVID cure circulating again,"[Fake, news, about, COVID, cure, circulating, again]"
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔,Total deaths reached M worldwide,Total deaths reached M worldwide,"[Total, deaths, reached, M, worldwide]"
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th,RT Lockdown extended until April th,RT Lockdown extended until April th,"[RT, Lockdown, extended, until, April, th]"

**Stopwords Removal**

In [80]:
import nltk
from nltk.corpus import stopwords

# NLP Preprocessing - Step 2: Stopword Removal

# Get English stopwords list
stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    """
    Remove common stopwords from token list
    Stopwords are common words that don't carry significant meaning
    Examples: is, am, are, the, a, an, etc.
    Specifically, 'WHO' will be preserved.
    """
    return [word for word in tokens if word.lower() not in stop_words or word == "WHO"]

# Apply stopword removal
df['No_Stopwords'] = df['Tokens'].apply(remove_stopwords)

print("="*70)
print("📌 NLP STEP 2: STOPWORD REMOVAL")
print("="*70)

print("\n🔹 Before vs After Stopword Removal:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['Tokens']}")
    print(f"After:  {row['No_Stopwords']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER STOPWORD REMOVAL")
print("="*70)
display(df)

======================================================================
📌 NLP STEP 2: STOPWORD REMOVAL
======================================================================

🔹 Before vs After Stopword Removal:


ID 1:
Before: ['Just', 'tested', 'positive', 'for', 'COVID']
After:  ['tested', 'positive', 'COVID']
------------------------------------------------------------

ID 2:
Before: ['WHO', 'reports', 'new', 'cases', 'today']
After:  ['WHO', 'reports', 'new', 'cases', 'today']
------------------------------------------------------------

ID 3:
Before: ['Get', 'vaccinated', 'ASAP', 'Vaccines', 'save', 'lives']
After:  ['Get', 'vaccinated', 'ASAP', 'Vaccines', 'save', 'lives']
------------------------------------------------------------

ID 4:
Before: ['RT', 'Mask', 'up', 'Cases', 'rising', 'again', 'in', 'Europe']
After:  ['RT', 'Mask', 'Cases', 'rising', 'Europe']
------------------------------------------------------------

ID 5:
Before: ['Covid', 'cases', 'increased', 'by', 'this', 'week']
After:  ['Covid', 'cases', 'increased', 'week']
------------------------------------------------------------

ID 6:
Before: ['BREAKING', 'New', 'variant', 'detected', 'in', 'South', 'Africa']
After:  ['BREAKING', 'New', 'variant', 'detected', 'South', 'Africa']
------------------------------------------------------------

ID 7:
Before: ['Plz', 'wear', 'mask', 'maintain', 'social', 'distance']
After:  ['Plz', 'wear', 'mask', 'maintain', 'social', 'distance']
------------------------------------------------------------

ID 8:
Before: ['Hospitalizations', 'up', 'by', 'patients', 'this', 'month']
After:  ['Hospitalizations', 'patients', 'month']
------------------------------------------------------------

ID 9:
Before: ['Booster', 'dose', 'available', 'for', 'from', 'March', 'st']
After:  ['Booster', 'dose', 'available', 'March', 'st']
------------------------------------------------------------

ID 10:
Before: ['Fake', 'news', 'about', 'COVID', 'cure', 'circulating', 'again']
After:  ['Fake', 'news', 'COVID', 'cure', 'circulating']
------------------------------------------------------------

ID 11:
Before: ['Total', 'deaths', 'reached', 'M', 'worldwide']
After:  ['Total', 'deaths', 'reached', 'worldwide']
------------------------------------------------------------

ID 12:
Before: ['RT', 'Lockdown', 'extended', 'until', 'April', 'th']
After:  ['RT', 'Lockdown', 'extended', 'April', 'th']
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER STOPWORD REMOVAL
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers,No_Punctuation,Cleaned_Regex,Tokens,No_Stopwords
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢,Just tested positive for COVID,Just tested positive for COVID,"[Just, tested, positive, for, COVID]","[tested, positive, COVID]"
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!",WHO reports new cases today,WHO reports new cases today,"[WHO, reports, new, cases, today]","[WHO, reports, new, cases, today]"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP Vaccines save lives,Get vaccinated ASAP Vaccines save lives,"[Get, vaccinated, ASAP, Vaccines, save, lives]","[Get, vaccinated, ASAP, Vaccines, save, lives]"
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,RT Mask up Cases rising again in Europe,RT Mask up Cases rising again in Europe,"[RT, Mask, up, Cases, rising, again, in, Europe]","[RT, Mask, Cases, rising, Europe]"
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week,Covid cases increased by this week,Covid cases increased by this week,"[Covid, cases, increased, by, this, week]","[Covid, cases, increased, week]"
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!,BREAKING New variant detected in South Africa,BREAKING New variant detected in South Africa,"[BREAKING, New, variant, detected, in, South, Africa]","[BREAKING, New, variant, detected, South, Africa]"
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏,Plz wear mask maintain social distance,Plz wear mask maintain social distance,"[Plz, wear, mask, maintain, social, distance]","[Plz, wear, mask, maintain, social, distance]"
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!,Hospitalizations up by patients this month,Hospitalizations up by patients this month,"[Hospitalizations, up, by, patients, this, month]","[Hospitalizations, patients, month]"
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st,Booster dose available for from March st,Booster dose available for from March st,"[Booster, dose, available, for, from, March, st]","[Booster, dose, available, March, st]"
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again,Fake news about COVID cure circulating again,"[Fake, news, about, COVID, cure, circulating, again]","[Fake, news, COVID, cure, circulating]"
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔,Total deaths reached M worldwide,Total deaths reached M worldwide,"[Total, deaths, reached, M, worldwide]","[Total, deaths, reached, worldwide]"
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th,RT Lockdown extended until April th,RT Lockdown extended until April th,"[RT, Lockdown, extended, until, April, th]","[RT, Lockdown, extended, April, th]"

**Stemming**

In [82]:
# NLP Preprocessing - Step 3: Stemming

# Initialize the Porter Stemmer
stemmer = PorterStemmer()

def stem_words(tokens):
    """
    Reduce words to their root form by removing suffixes
    Example: running -> run, studies -> studi, better -> better
    Note: Stemming may not return actual dictionary words
    """
    return [stemmer.stem(word) for word in tokens]

# Apply stemming
df['Stemmed'] = df['No_Stopwords'].apply(stem_words)

print("="*70)
print("📌 NLP STEP 3: STEMMING")
print("="*70)

print("\n🔹 Before vs After Stemming:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['No_Stopwords']}")
    print(f"After:  {row['Stemmed']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER STEMMING")
print("="*70)
display(df)

======================================================================
📌 NLP STEP 3: STEMMING
======================================================================

🔹 Before vs After Stemming:


ID 1:
Before: ['tested', 'positive', 'COVID']
After:  ['test', 'posit', 'covid']
------------------------------------------------------------

ID 2:
Before: ['WHO', 'reports', 'new', 'cases', 'today']
After:  ['who', 'report', 'new', 'case', 'today']
------------------------------------------------------------

ID 3:
Before: ['Get', 'vaccinated', 'ASAP', 'Vaccines', 'save', 'lives']
After:  ['get', 'vaccin', 'asap', 'vaccin', 'save', 'live']
------------------------------------------------------------

ID 4:
Before: ['RT', 'Mask', 'Cases', 'rising', 'Europe']
After:  ['rt', 'mask', 'case', 'rise', 'europ']
------------------------------------------------------------

ID 5:
Before: ['Covid', 'cases', 'increased', 'week']
After:  ['covid', 'case', 'increas', 'week']
------------------------------------------------------------

ID 6:
Before: ['BREAKING', 'New', 'variant', 'detected', 'South', 'Africa']
After:  ['break', 'new', 'variant', 'detect', 'south', 'africa']
------------------------------------------------------------

ID 7:
Before: ['Plz', 'wear', 'mask', 'maintain', 'social', 'distance']
After:  ['plz', 'wear', 'mask', 'maintain', 'social', 'distanc']
------------------------------------------------------------

ID 8:
Before: ['Hospitalizations', 'patients', 'month']
After:  ['hospit', 'patient', 'month']
------------------------------------------------------------

ID 9:
Before: ['Booster', 'dose', 'available', 'March', 'st']
After:  ['booster', 'dose', 'avail', 'march', 'st']
------------------------------------------------------------

ID 10:
Before: ['Fake', 'news', 'COVID', 'cure', 'circulating']
After:  ['fake', 'news', 'covid', 'cure', 'circul']
------------------------------------------------------------

ID 11:
Before: ['Total', 'deaths', 'reached', 'worldwide']
After:  ['total', 'death', 'reach', 'worldwid']
------------------------------------------------------------

ID 12:
Before: ['RT', 'Lockdown', 'extended', 'April', 'th']
After:  ['rt', 'lockdown', 'extend', 'april', 'th']
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER STEMMING
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers,No_Punctuation,Cleaned_Regex,Tokens,No_Stopwords,Stemmed
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢,Just tested positive for COVID,Just tested positive for COVID,"[Just, tested, positive, for, COVID]","[tested, positive, COVID]","[test, posit, covid]"
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!",WHO reports new cases today,WHO reports new cases today,"[WHO, reports, new, cases, today]","[WHO, reports, new, cases, today]","[who, report, new, case, today]"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP Vaccines save lives,Get vaccinated ASAP Vaccines save lives,"[Get, vaccinated, ASAP, Vaccines, save, lives]","[Get, vaccinated, ASAP, Vaccines, save, lives]","[get, vaccin, asap, vaccin, save, live]"
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,RT Mask up Cases rising again in Europe,RT Mask up Cases rising again in Europe,"[RT, Mask, up, Cases, rising, again, in, Europe]","[RT, Mask, Cases, rising, Europe]","[rt, mask, case, rise, europ]"
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week,Covid cases increased by this week,Covid cases increased by this week,"[Covid, cases, increased, by, this, week]","[Covid, cases, increased, week]","[covid, case, increas, week]"
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!,BREAKING New variant detected in South Africa,BREAKING New variant detected in South Africa,"[BREAKING, New, variant, detected, in, South, Africa]","[BREAKING, New, variant, detected, South, Africa]","[break, new, variant, detect, south, africa]"
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏,Plz wear mask maintain social distance,Plz wear mask maintain social distance,"[Plz, wear, mask, maintain, social, distance]","[Plz, wear, mask, maintain, social, distance]","[plz, wear, mask, maintain, social, distanc]"
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!,Hospitalizations up by patients this month,Hospitalizations up by patients this month,"[Hospitalizations, up, by, patients, this, month]","[Hospitalizations, patients, month]","[hospit, patient, month]"
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st,Booster dose available for from March st,Booster dose available for from March st,"[Booster, dose, available, for, from, March, st]","[Booster, dose, available, March, st]","[booster, dose, avail, march, st]"
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again,Fake news about COVID cure circulating again,"[Fake, news, about, COVID, cure, circulating, again]","[Fake, news, COVID, cure, circulating]","[fake, news, covid, cure, circul]"
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔,Total deaths reached M worldwide,Total deaths reached M worldwide,"[Total, deaths, reached, M, worldwide]","[Total, deaths, reached, worldwide]","[total, death, reach, worldwid]"
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th,RT Lockdown extended until April th,RT Lockdown extended until April th,"[RT, Lockdown, extended, until, April, th]","[RT, Lockdown, extended, April, th]","[rt, lockdown, extend, april, th]"

**Lammatization**

In [83]:
# NLP Preprocessing - Step 4: Lemmatization

# Initialize the WordNet Lemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_words(tokens):
    """
    Reduce words to their base form (lemma) using dictionary
    Example: running -> run, better -> good, studies -> study
    Note: Lemmatization returns actual dictionary words
    """
    return [lemmatizer.lemmatize(word) for word in tokens]

# Apply lemmatization
df['Lemmatized'] = df['Stemmed'].apply(lemmatize_words)

print("="*70)
print("📌 NLP STEP 4: LEMMATIZATION")
print("="*70)

print("\n🔹 Before vs After Lemmatization:\n")

for idx, row in df.iterrows():
    print(f"\nID {row['ID']}:")
    print(f"Before: {row['Stemmed']}")
    print(f"After:  {row['Lemmatized']}")
    print("-"*60)

print("\n" + "="*70)
print("📊 DATAFRAME AFTER LEMMATIZATION")
print("="*70)
display(df)

======================================================================
📌 NLP STEP 4: LEMMATIZATION
======================================================================

🔹 Before vs After Lemmatization:


ID 1:
Before: ['test', 'posit', 'covid']
After:  ['test', 'posit', 'covid']
------------------------------------------------------------

ID 2:
Before: ['who', 'report', 'new', 'case', 'today']
After:  ['who', 'report', 'new', 'case', 'today']
------------------------------------------------------------

ID 3:
Before: ['get', 'vaccin', 'asap', 'vaccin', 'save', 'live']
After:  ['get', 'vaccin', 'asap', 'vaccin', 'save', 'live']
------------------------------------------------------------

ID 4:
Before: ['rt', 'mask', 'case', 'rise', 'europ']
After:  ['rt', 'mask', 'case', 'rise', 'europ']
------------------------------------------------------------

ID 5:
Before: ['covid', 'case', 'increas', 'week']
After:  ['covid', 'case', 'increas', 'week']
------------------------------------------------------------

ID 6:
Before: ['break', 'new', 'variant', 'detect', 'south', 'africa']
After:  ['break', 'new', 'variant', 'detect', 'south', 'africa']
------------------------------------------------------------

ID 7:
Before: ['plz', 'wear', 'mask', 'maintain', 'social', 'distanc']
After:  ['plz', 'wear', 'mask', 'maintain', 'social', 'distanc']
------------------------------------------------------------

ID 8:
Before: ['hospit', 'patient', 'month']
After:  ['hospit', 'patient', 'month']
------------------------------------------------------------

ID 9:
Before: ['booster', 'dose', 'avail', 'march', 'st']
After:  ['booster', 'dose', 'avail', 'march', 'st']
------------------------------------------------------------

ID 10:
Before: ['fake', 'news', 'covid', 'cure', 'circul']
After:  ['fake', 'news', 'covid', 'cure', 'circul']
------------------------------------------------------------

ID 11:
Before: ['total', 'death', 'reach', 'worldwid']
After:  ['total', 'death', 'reach', 'worldwid']
------------------------------------------------------------

ID 12:
Before: ['rt', 'lockdown', 'extend', 'april', 'th']
After:  ['rt', 'lockdown', 'extend', 'april', 'th']
------------------------------------------------------------

======================================================================
📊 DATAFRAME AFTER LEMMATIZATION
======================================================================

,ID,Text,Lemmatized,Final_Cleaned_Text,No_URLs,No_Mentions,Hashtags,No_Hashtags,No_Numbers,No_Punctuation,Cleaned_Regex,Tokens,No_Stopwords,Stemmed
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,"[test, posit, covid]",test posit covid,Just tested positive for COVID-19 😢 #COVID19,Just tested positive for COVID-19 😢 #COVID19,[#COVID19],Just tested positive for COVID-19 😢,Just tested positive for COVID- 😢,Just tested positive for COVID,Just tested positive for COVID,"[Just, tested, positive, for, COVID]","[tested, positive, COVID]","[test, posit, covid]"
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","[who, report, new, case, today]",who report new case today,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic","WHO reports 50,000 new cases today! #Pandemic",[#Pandemic],"WHO reports 50,000 new cases today!","WHO reports , new cases today!",WHO reports new cases today,WHO reports new cases today,"[WHO, reports, new, cases, today]","[WHO, reports, new, cases, today]","[who, report, new, case, today]"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,"[get, vaccin, asap, vaccin, save, live]",get vaccin asap vaccin save live,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,[#VaccineWorks],Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP!! 💉 Vaccines save lives,Get vaccinated ASAP Vaccines save lives,Get vaccinated ASAP Vaccines save lives,"[Get, vaccinated, ASAP, Vaccines, save, lives]","[Get, vaccinated, ASAP, Vaccines, save, lives]","[get, vaccin, asap, vaccin, save, live]"
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,"[rt, mask, case, rise, europ]",rt mask case rise europ,RT @healthmin: Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,[],RT : Mask up! Cases rising again in Europe,RT : Mask up! Cases rising again in Europe,RT Mask up Cases rising again in Europe,RT Mask up Cases rising again in Europe,"[RT, Mask, up, Cases, rising, again, in, Europe]","[RT, Mask, Cases, rising, Europe]","[rt, mask, case, rise, europ]"
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,"[covid, case, increas, week]",covid case increas week,Covid cases increased by 25% this week #Coronavirus @nytimes,Covid cases increased by 25% this week #Coronavirus,[#Coronavirus],Covid cases increased by 25% this week,Covid cases increased by % this week,Covid cases increased by this week,Covid cases increased by this week,"[Covid, cases, increased, by, this, week]","[Covid, cases, increased, week]","[covid, case, increas, week]"
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,"[break, new, variant, detect, south, africa]",break new variant detect south africa,BREAKING: New variant detected in South Africa! #Omicron @WHO,BREAKING: New variant detected in South Africa! #Omicron,[#Omicron],BREAKING: New variant detected in South Africa!,BREAKING: New variant detected in South Africa!,BREAKING New variant detected in South Africa,BREAKING New variant detected in South Africa,"[BREAKING, New, variant, detected, in, South, Africa]","[BREAKING, New, variant, detected, South, Africa]","[break, new, variant, detect, south, africa]"
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[plz, wear, mask, maintain, social, distanc]",plz wear mask maintain social distanc,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,"[#StaySafe, #COVID]",Plz wear mask & maintain social distance 🙏,Plz wear mask & maintain social distance 🙏,Plz wear mask maintain social distance,Plz wear mask maintain social distance,"[Plz, wear, mask, maintain, social, distance]","[Plz, wear, mask, maintain, social, distance]","[plz, wear, mask, maintain, social, distanc]"
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,"[hospit, patient, month]",hospit patient month,Hospitalizations up by 1000 patients this month!!! @CDCgov,Hospitalizations up by 1000 patients this month!!!,[],Hospitalizations up by 1000 patients this month!!!,Hospitalizations up by patients this month!!!,Hospitalizations up by patients this month,Hospitalizations up by patients this month,"[Hospitalizations, up, by, patients, this, month]","[Hospitalizations, patients, month]","[hospit, patient, month]"
8,9,Booster dose available for 18+ from March 1st #BoosterDose,"[booster, dose, avail, march, st]",booster dose avail march st,Booster dose available for 18+ from March 1st #BoosterDose,Booster dose available for 18+ from March 1st #BoosterDose,[#BoosterDose],Booster dose available for 18+ from March 1st,Booster dose available for + from March st,Booster dose available for from March st,Booster dose available for from March st,"[Booster, dose, available, for, from, March, st]","[Booster, dose, available, March, st]","[booster, dose, avail, march, st]"
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,"[fake, news, covid, cure, circul]",fake news covid cure circul,Fake news about COVID cure circulating again!! #StopMisinformation,Fake news about COVID cure circulating again!! #StopMisinformation,[#StopMisinformation],Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again!!,Fake news about COVID cure circulating again,Fake news about COVID cure circulating again,"[Fake, news, about, COVID, cure, circulating, again]","[Fake, news, COVID, cure, circulating]","[fake, news, covid, cure, circul]"
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[total, death, reach, worldwid]",total death reach worldwid,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,"[#RIP, #COVID19]",Total deaths reached 6.5M worldwide 💔,Total deaths reached .M worldwide 💔,Total deaths reached M worldwide,Total deaths reached M worldwide,"[Total, deaths, reached, M, worldwide]","[Total, deaths, reached, worldwide]","[total, death, reach, worldwid]"
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,"[rt, lockdown, extend, april, th]",rt lockdown extend april th,RT @gov: Lockdown extended until April 15th @official,RT : Lockdown extended until April 15th,[],RT : Lockdown extended until April 15th,RT : Lockdown extended until April th,RT Lockdown extended until April th,RT Lockdown extended until April th,"[RT, Lockdown, extended, until, April, th]","[RT, Lockdown, extended, April, th]","[rt, lockdown, extend, april, th]"

**Celaned Dataset**

In [84]:
import pandas as pd

# Final Step: Display Complete Cleaned Dataset

# Create a final cleaned text column by joining tokens
def join_tokens(tokens):
    return ' '.join(tokens)

df['Final_Cleaned_Text'] = df['Lemmatized'].apply(join_tokens)

print("="*70)
print("📌 FINAL CLEANED DATASET - READY FOR ANALYSIS")
print("="*70)

# Display only essential columns for final output
final_df = df[['ID', 'Text', 'Final_Cleaned_Text', 'Lemmatized']]
display(final_df)

======================================================================
📌 FINAL CLEANED DATASET - READY FOR ANALYSIS
======================================================================

,ID,Text,Final_Cleaned_Text,Lemmatized
0,1,Just tested positive for COVID-19 😢 #COVID19 https://t.co/abc123,test posit covid,"[test, posit, covid]"
1,2,"WHO reports 50,000 new cases today! @WHO @CDC #Pandemic",who report new case today,"[who, report, new, case, today]"
2,3,Get vaccinated ASAP!! 💉 Vaccines save lives #VaccineWorks,get vaccin asap vaccin save live,"[get, vaccin, asap, vaccin, save, live]"
3,4,RT @healthmin: Mask up! Cases rising again in Europe https://t.co/xyz789,rt mask case rise europ,"[rt, mask, case, rise, europ]"
4,5,Covid cases increased by 25% this week #Coronavirus @nytimes,covid case increas week,"[covid, case, increas, week]"
5,6,BREAKING: New variant detected in South Africa! #Omicron @WHO,break new variant detect south africa,"[break, new, variant, detect, south, africa]"
6,7,Plz wear mask & maintain social distance 🙏 #StaySafe #COVID,plz wear mask maintain social distanc,"[plz, wear, mask, maintain, social, distanc]"
7,8,Hospitalizations up by 1000 patients this month!!! @CDCgov,hospit patient month,"[hospit, patient, month]"
8,9,Booster dose available for 18+ from March 1st #BoosterDose,booster dose avail march st,"[booster, dose, avail, march, st]"
9,10,Fake news about COVID cure circulating again!! #StopMisinformation,fake news covid cure circul,"[fake, news, covid, cure, circul]"
10,11,Total deaths reached 6.5M worldwide 💔 #RIP #COVID19,total death reach worldwid,"[total, death, reach, worldwid]"
11,12,RT @gov: Lockdown extended until April 15th https://t.co/def456 @official,rt lockdown extend april th,"[rt, lockdown, extend, april, th]"